

1. SELECT * 
FROM ROLE  
FULL JOIN USER_NEW 
ON ROLE.ID = USER_NEW.ROLE_ID 
ORDER BY ROLE.NAME ASC, USER_NEW.NAME ASC;

2.
SELECT * 
FROM ROLE  
RIGHT JOIN USER_NEW 
ON ROLE.ID = USER_NEW.ROLE_ID 
ORDER BY ROLE.NAME ASC, USER_NEW.NAME ASC;

3.
SELECT USER_NEW.NAME 
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID;

4.
SELECT user_new.phonenumber, user_new.emailid, profile.batch, department.name, profile.designation, experience.company_name
FROM ((USER_NEW INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID) (INNER JOIN DEGREE ON PROFILE.DEGREE_ID = DEGREE.ID)
(INNER JOIN DEPARTMENT ON DEGREE.DEPARTMENT_ID = DEPARTMENT.ID)(INNER JOIN EXPERIENCE ON profile.id = experience.profile_id ))
WHERE user_new.name = 'ProGrad' and experience.currentvalue=3 ;

5.
SELECT USER_NEW.NAME 
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
INNER JOIN PROFILE_SKILLS ON PROFILE.ID = PROFILE_SKILLS.PROFILE_ID
where role.name='ALUMINI' ORDER BY  user_new.name ASC, skill.NAME ASC;

6.
SELECT user_new.name, experience.company_name
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
INNER JOIN EXPERIENCE ON profile.id = experience.profile_id 
WHERE ROLE.NAME = 'ALUMINI'
ORDER BY user_name.name ASC, experience.company_name ASC ;

7.
SELECT user_new.name, experience.company_name
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
INNER JOIN EXPERIENCE ON profile.id = experience.profile_id 
WHERE ROLE.NAME = 'ALUMINI'
ORDER BY user_name.name ASC, experience.company_name ASC ;

8.
SELECT user_new.name, experience.company_name
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
INNER JOIN EXPERIENCE ON profile.id = experience.profile_id 
WHERE role.name='Alumni' AND experience.currentValue=1
ORDER BY USER_NEW.NAME ;

9.

SELECT user_new.name, experience.company_name
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
INNER JOIN EXPERIENCE ON profile.id = experience.profile_id 
WHERE role.name='Alumni' AND experience.currentValue=1 AND profile.batch='2008'
ORDER BY USER_NEW.NAME ;

10.

SELECT user_new.name, user_new.emailid, user_new.phonenumber, profile.address
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
WHERE role.name='Alumni' AND user_new.profile_id IS NOT NULL
ORDER BY USER_NEW.NAME ;

11.
SELECT user_new.name, user_new.emailid, user_new.phonenumber, profile.address
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
WHERE role.name='Alumni' AND profile.batch='2008'
ORDER BY USER_NEW.NAME ;


12.
SELECT user_new.name, user_new.emailid, user_new.phonenumber, profile.address
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
INNER JOIN DEGREE ON PROFILE.DEGREE_ID = DEGREE.ID
WHERE role.name='Alumni' AND degree.name='BSC_CT'
ORDER BY USER_NEW.NAME ;

13.
SELECT user_new.name, user_new.emailid, user_new.phonenumber, profile.address
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
INNER JOIN DEGREE ON PROFILE.DEGREE_ID = DEGREE.ID
INNER JOIN DEPARTMENT ON DEGREE.DEPARTMENT_ID = DEPARTMENT.ID
WHERE role.name='Alumni' AND department.name='CSE'
ORDER BY USER_NEW.NAME ;

14.
SELECT user_new.name, higher_degree.university_name
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
INNER JOIN HIGHER_DEGREE ON PROFILE.ID = HIGHER_DEGREE.PROFILE_ID
WHERE role.name='Alumni' AND higher_degree.degree_name IS NOT NULL
ORDER BY USER_NEW.NAME ASC,higher_degree.university_name ASC ;

15.
SELECT user_new.name, higher_degree.university_name
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
INNER JOIN HIGHER_DEGREE ON PROFILE.ID = HIGHER_DEGREE.PROFILE_ID
WHERE role.name='Alumni' AND higher_degree.degree_name IS NOT NULL
ORDER BY USER_NEW.NAME ASC,higher_degree.university_name ASC ;

16.
SELECT user_new.name, user_new.emailid, user_new.phonenumber, profile.address
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
INNER JOIN DEGREE ON PROFILE.DEGREE_ID = DEGREE.ID
INNER JOIN DEPARTMENT ON DEGREE.DEPARTMENT_ID = DEPARTMENT.ID
INNER JOIN HIGHER_DEGREE ON PROFILE.ID = HIGHER_DEGREE.PROFILE_ID
WHERE role.name='Alumni' AND higher_degree.university_name='Texas University'
ORDER BY USER_NEW.NAME ;

17.
SELECT user_new.name, profile.batch
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
WHERE role.name='Alumni' and profile.gender='female'
ORDER BY USER_NEW.NAME ;

18.
SELECT user_new.name, profile.batch, degree.name
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
INNER JOIN DEGREE ON PROFILE.DEGREE_ID = DEGREE.ID
WHERE role.name='Alumni' AND profile.gender='female'
ORDER BY USER_NEW.NAME ;

19.
SELECT user_new.name, profile.batch, degree.name, department.name
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
INNER JOIN DEGREE ON PROFILE.DEGREE_ID = DEGREE.ID
INNER JOIN DEPARTMENT ON DEGREE.DEPARTMENT_ID = DEPARTMENT.ID
WHERE role.name='Alumni' AND profile.gender='female'
ORDER BY USER_NEW.NAME ;

19.1

SELECT degree.name, department.name
FROM DEGREE INNER JOIN DEPARTMENT ON DEGREE.DEPARTMENT_ID = DEPARTMENT.ID
ORDER BY DEGREE.NAME ;

20.
SELECT user_new.name, profile.designation
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
WHERE  role.name='Alumni' and profile.gender='male'
ORDER BY USER_NEW.NAME ;

21.

SELECT user_new.name, profile.designation
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
INNER JOIN EXPERIENCE ON PROFILE.ID = EXPERIENCE.PROFILE_ID
WHERE  role.name='Alumni' AND experience.currentValue=1 AND experience.company_name='TCS'
ORDER BY USER_NEW.NAME ;

22.
SELECT user_new.name, querytable.content
FROM USER_NEW INNER JOIN QUERYTABLE ON USER_NEW.ID = QUERYTABLE.USER_ID
ORDER BY USER_NEW.NAME ;

23.
SELECT user_new.name, querytable.content
FROM USER_NEW INNER JOIN QUERYTABLE ON USER_NEW.ID = QUERYTABLE.USER_ID
WHERE PARENT_ID IS NOT NULL
ORDER BY USER_NEW.NAME ;

24.
SELECT user_new.name, post.content
FROM USER_NEW INNER JOIN POST ON USER_NEW.ID = POST.USER_ID
ORDER BY USER_NEW.NAME ;

25.
SELECT user_new.name, post.content
FROM USER_NEW INNER JOIN POST ON USER_NEW.ID = POST.USER_ID
WHERE post_type.name='Technology'
ORDER BY USER_NEW.NAME ;

26.
SELECT user_new.name, post.content
FROM USER_NEW INNER JOIN POST ON USER_NEW.ID = POST.USER_ID
WHERE post.dateof='2013'
ORDER BY USER_NEW.NAME ;

27.
SELECT user_new.name, department.name
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN PROFILE ON USER_NEW.PROFILE_ID = PROFILE.ID
INNER JOIN DEGREE ON PROFILE.DEGREE_ID = DEGREE.ID
INNER JOIN DEPARTMENT ON DEGREE.DEPARTMENT_ID = DEPARTMENT.ID
INNER JOID PROFILE_SKILLS ON PROFILE.ID = PROFILE_SKILLS.PROFILE_ID
INNER JOIN SKILL ON PROFILE_SKILLS.SKILL_ID = SKILL.ID
WHERE skill.name='Programming'
ORDER BY USER_NEW.NAME ;

28.
SELECT user_new.name, event.name
FROM USER_NEW INNER JOIN EVENT ON USER_NEW.ID = EVENT.ORGANIZER_ID
WHERE role.name='Alumni'
ORDER BY user_new.name ASC, event.dateof DESC;

29.
SELECT user_new.name, event.name
FROM USER_NEW INNER JOIN ROLE ON USER_NEW.ROLE_ID = ROLE.ID
INNER JOIN EVENT ON USER_NEW.ID = EVENT.ORGANIZER_ID
WHERE role.name='Alumni'
ORDER BY user_new.name ASC, event.dateof ASC;














































